spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/temp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: yuanjy
    driver-class-name: com.mysql.jdbc.Driver
flyway:
  baseline-on-migrate: false
logging:
  path: /data/logs/springboot/test
  level: info